### ISSUE TITLE
AWS Secrets doesan't install on R 3.5

### ISSUE THREAD

**Issue by lissahyacinth** [cloudyr/aws.secrets#2]
Possible bug in installation from Git master - I think it's due to the list in credentials_to_list

return(list(key = key, secret = secret, session_token = session_token, region = region))

As adding in else statements with NULLs for key, secret, session_token, etc, fixes the installation. Added example on PR.

> remotes::install_github("cloudyr/aws.signature")
Downloading GitHub repo cloudyr/aws.signature@master
✔  checking for file ‘/private/var/folders/np/fy2_8btj5334yh48qbl9m1rm0000gq/T/Rtmpd3rB2U/remotes156fd7b6f2753/cloudyr-aws.signature-df1ddb4/DESCRIPTION’ ...
─  preparing ‘aws.signature’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘aws.signature_0.4.5.tar.gz’
   
Installing package into ‘/Users/lissa.hyacinth/Rlibs’
(as ‘lib’ is unspecified)
* installing *source* package ‘aws.signature’ ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘aws.signature’:
 .onLoad failed in loadNamespace() for 'aws.signature', details:
  call: credentials_to_list(cred, region = region, default_region = default_region, 
  error: object 'key' not found
Error: loading failed
Execution halted
``

**Comment by lgjohnson** [comment]
@lissahyacinth were you able to resolve this bug? I'm running into the same issue with `R 3.5.0`. I have the following Rocker image:

```
FROM rocker/verse:3.5.0

WORKDIR /home/rstudio/work

RUN Rscript -e "install.packages(c('aws.s3', 'aws.signature'), repos = c('cloudyr' = 'http://cloudyr.github.io/drat'))"
```

When I start up Rstudio in the container and run `library(aws.s3)` or  `library(aws.signature)` I get the same error as you:

```
> library(aws.s3)
Error : .onLoad failed in loadNamespace() for 'aws.signature', details:
  call: credentials_to_list(cred, region = region, default_region = default_region, 
  error: object 'key' not found
Error: package or namespace load failed for ‘aws.s3’
```

**Comment by lissahyacinth** [comment]
I did! It turned out to be an issue with aws.signature which is why I closed it here, but never finished sending a PR to aws.signature to fix it, as I couldn't recreate the bug when trying to show the fix. 

The error seemed to be within https://github.com/cloudyr/aws.signature/blob/master/R/locate_credentials.R#L354 - If you add NULL statements for key, secret, and session token, such as 

```
if (!is.null(cred[["AWS_ACCESS_KEY_ID"]])) {
        key <- cred[["AWS_ACCESS_KEY_ID"]]
        if (isTRUE(verbose)) {
            message("Using value in credentials file for AWS Access Key ID")
        }
    } else {
key <- NULL
}
```

Then it'll build, and you can install it. The error should only occur when there is literally *no* AWS credentials anywhere on the machine and for some reason R is ignoring the default for them. I tried the command you wrote, and it worked, and all three of the machines I've tested (2 mac / 1 windows) aren't showing the error regardless of what I do.

Just realised you're managing it on an image, so I'll look into the image itself later to try and recreate it as telling you to edit a file to install every time you build is a bit unwieldy!

**Comment by lgjohnson** [comment]
Hey @lissahyacinth , thanks for pointing me towards that file! I looked upstream from `credentials_to_list` and found that in the function `locate_credentials`, creds are read in as a named list (where the profile are the keys) and then subset twice, resulting in a NULL being passed in for the `cred` argument to `credentials_to_list`. Check out: https://github.com/cloudyr/aws.signature/blob/master/R/locate_credentials.R#L253
and in lines 255 and 257.
I submitted a PR hopefully fixing this issue [here](https://github.com/cloudyr/aws.signature/pull/40).
